export interface Doctor {
  id: string
  name: string
  specialty: string
  experience: number
  qualification: string
  hospital: string
  location: string
  rating: number
  consultationFee: number
  availableSlots: string[]
  image?: string
}

export const mockDoctors: Doctor[] = [
  {
    id: "1",
    name: "Dr. Rajesh Kumar",
    specialty: "Cardiologist",
    experience: 15,
    qualification: "MBBS, MD (Cardiology)",
    hospital: "Punjab Heart Institute",
    location: "Ludhiana",
    rating: 4.8,
    consultationFee: 800,
    availableSlots: ["09:00", "10:00", "11:00", "14:00", "15:00", "16:00"],
  },
  {
    id: "2",
    name: "Dr. Priya Sharma",
    specialty: "Pediatrician",
    experience: 12,
    qualification: "MBBS, MD (Pediatrics)",
    hospital: "Children Hospital Amritsar",
    location: "Amritsar",
    rating: 4.9,
    consultationFee: 600,
    availableSlots: ["09:30", "10:30", "11:30", "14:30", "15:30", "16:30"],
  },
  {
    id: "3",
    name: "Dr. Harpreet Singh",
    specialty: "Orthopedic",
    experience: 18,
    qualification: "MBBS, MS (Orthopedics)",
    hospital: "Bone & Joint Clinic",
    location: "Jalandhar",
    rating: 4.7,
    consultationFee: 900,
    availableSlots: ["08:00", "09:00", "10:00", "15:00", "16:00", "17:00"],
  },
  {
    id: "4",
    name: "Dr. Simran Kaur",
    specialty: "Gynecologist",
    experience: 10,
    qualification: "MBBS, MD (Gynecology)",
    hospital: "Women Care Hospital",
    location: "Patiala",
    rating: 4.6,
    consultationFee: 700,
    availableSlots: ["09:00", "10:00", "11:00", "14:00", "15:00"],
  },
  {
    id: "5",
    name: "Dr. Amarjeet Singh",
    specialty: "Neurologist",
    experience: 20,
    qualification: "MBBS, DM (Neurology)",
    hospital: "Neuro Care Center",
    location: "Ludhiana",
    rating: 4.9,
    consultationFee: 1200,
    availableSlots: ["10:00", "11:00", "12:00", "15:00", "16:00"],
  },
  {
    id: "6",
    name: "Dr. Manpreet Kaur",
    specialty: "Dermatologist",
    experience: 8,
    qualification: "MBBS, MD (Dermatology)",
    hospital: "Skin Care Clinic",
    location: "Mohali",
    rating: 4.5,
    consultationFee: 650,
    availableSlots: ["09:00", "10:00", "11:00", "14:00", "15:00", "16:00"],
  },
  {
    id: "7",
    name: "Dr. Jasbir Singh",
    specialty: "General Physician",
    experience: 25,
    qualification: "MBBS, MD (Internal Medicine)",
    hospital: "City Hospital",
    location: "Bathinda",
    rating: 4.4,
    consultationFee: 500,
    availableSlots: ["08:00", "09:00", "10:00", "11:00", "14:00", "15:00", "16:00", "17:00"],
  },
  {
    id: "8",
    name: "Dr. Gurpreet Kaur",
    specialty: "Psychiatrist",
    experience: 14,
    qualification: "MBBS, MD (Psychiatry)",
    hospital: "Mental Health Center",
    location: "Amritsar",
    rating: 4.7,
    consultationFee: 800,
    availableSlots: ["10:00", "11:00", "14:00", "15:00", "16:00"],
  },
  {
    id: "9",
    name: "Dr. Ravi Kumar",
    specialty: "ENT Specialist",
    experience: 16,
    qualification: "MBBS, MS (ENT)",
    hospital: "ENT Care Hospital",
    location: "Jalandhar",
    rating: 4.6,
    consultationFee: 750,
    availableSlots: ["09:00", "10:00", "11:00", "15:00", "16:00"],
  },
  {
    id: "10",
    name: "Dr. Navdeep Singh",
    specialty: "Urologist",
    experience: 13,
    qualification: "MBBS, MCh (Urology)",
    hospital: "Urology Center",
    location: "Patiala",
    rating: 4.5,
    consultationFee: 850,
    availableSlots: ["09:30", "10:30", "11:30", "14:30", "15:30"],
  },
  {
    id: "11",
    name: "Dr. Kuldeep Kaur",
    specialty: "Ophthalmologist",
    experience: 11,
    qualification: "MBBS, MS (Ophthalmology)",
    hospital: "Eye Care Center",
    location: "Mohali",
    rating: 4.8,
    consultationFee: 700,
    availableSlots: ["08:30", "09:30", "10:30", "14:30", "15:30", "16:30"],
  },
]
