export interface MedicalStore {
  id: string
  name: string
  ownerName: string
  phoneNumber: string
  address: string
  district: string
  mandal: string
  village: string
  licenseNumber: string
  openingHours: string
  services: string[]
  rating: number
  isVerified: boolean
  coordinates?: {
    lat: number
    lng: number
  }
}

export const mockMedicalStores: MedicalStore[] = [
  {
    id: "1",
    name: "Punjab Medical Store",
    ownerName: "Rajesh Kumar",
    phoneNumber: "9876543210",
    address: "Main Market, Model Town",
    district: "Ludhiana",
    mandal: "Ludhiana East",
    village: "Model Town",
    licenseNumber: "PB/LDH/2023/001",
    openingHours: "8:00 AM - 10:00 PM",
    services: ["Prescription Medicines", "OTC Drugs", "Medical Equipment", "Home Delivery"],
    rating: 4.5,
    isVerified: true,
    coordinates: { lat: 30.901, lng: 75.8573 },
  },
  {
    id: "2",
    name: "City Pharmacy",
    ownerName: "Priya Sharma",
    phoneNumber: "9876543211",
    address: "Civil Lines, Near Hospital",
    district: "Ludhiana",
    mandal: "Ludhiana Central",
    village: "Civil Lines",
    licenseNumber: "PB/LDH/2023/002",
    openingHours: "7:00 AM - 11:00 PM",
    services: ["Prescription Medicines", "OTC Drugs", "Baby Care", "24/7 Emergency"],
    rating: 4.7,
    isVerified: true,
    coordinates: { lat: 30.9, lng: 75.85 },
  },
  {
    id: "3",
    name: "Golden Medical Hall",
    ownerName: "Harpreet Singh",
    phoneNumber: "9876543212",
    address: "GT Road, Near Bus Stand",
    district: "Amritsar",
    mandal: "Amritsar East",
    village: "GT Road",
    licenseNumber: "PB/ASR/2023/001",
    openingHours: "6:00 AM - 12:00 AM",
    services: ["Prescription Medicines", "Ayurvedic Medicines", "Surgical Items"],
    rating: 4.3,
    isVerified: true,
    coordinates: { lat: 31.634, lng: 74.8723 },
  },
  {
    id: "4",
    name: "Health Plus Pharmacy",
    ownerName: "Simran Kaur",
    phoneNumber: "9876543213",
    address: "Mall Road, Central Market",
    district: "Amritsar",
    mandal: "Amritsar Central",
    village: "Mall Road",
    licenseNumber: "PB/ASR/2023/002",
    openingHours: "8:00 AM - 10:00 PM",
    services: ["Prescription Medicines", "Health Supplements", "Cosmetics"],
    rating: 4.6,
    isVerified: true,
    coordinates: { lat: 31.62, lng: 74.88 },
  },
  {
    id: "5",
    name: "Wellness Medical Store",
    ownerName: "Amarjeet Singh",
    phoneNumber: "9876543214",
    address: "Model Town Extension",
    district: "Jalandhar",
    mandal: "Jalandhar East",
    village: "Model Town Extension",
    licenseNumber: "PB/JLR/2023/001",
    openingHours: "7:30 AM - 9:30 PM",
    services: ["Prescription Medicines", "OTC Drugs", "Medical Devices"],
    rating: 4.4,
    isVerified: true,
    coordinates: { lat: 31.326, lng: 75.5762 },
  },
  {
    id: "6",
    name: "Care Medical Hall",
    ownerName: "Manpreet Kaur",
    phoneNumber: "9876543215",
    address: "Urban Estate, Phase 2",
    district: "Jalandhar",
    mandal: "Jalandhar West",
    village: "Urban Estate",
    licenseNumber: "PB/JLR/2023/002",
    openingHours: "8:00 AM - 10:00 PM",
    services: ["Prescription Medicines", "Baby Care", "Elderly Care"],
    rating: 4.8,
    isVerified: true,
    coordinates: { lat: 31.32, lng: 75.57 },
  },
  {
    id: "7",
    name: "Royal Pharmacy",
    ownerName: "Jasbir Singh",
    phoneNumber: "9876543216",
    address: "Leela Bhawan, Main Market",
    district: "Patiala",
    mandal: "Patiala Central",
    village: "Leela Bhawan",
    licenseNumber: "PB/PTL/2023/001",
    openingHours: "8:00 AM - 9:00 PM",
    services: ["Prescription Medicines", "Homeopathic Medicines", "Surgical Items"],
    rating: 4.2,
    isVerified: true,
    coordinates: { lat: 30.3398, lng: 76.3869 },
  },
  {
    id: "8",
    name: "New Life Medical Store",
    ownerName: "Gurpreet Kaur",
    phoneNumber: "9876543217",
    address: "Sector 67, Near Hospital",
    district: "Mohali",
    mandal: "Mohali East",
    village: "Sector 67",
    licenseNumber: "PB/MOH/2023/001",
    openingHours: "24 Hours",
    services: ["Prescription Medicines", "Emergency Medicines", "Medical Equipment", "Home Delivery"],
    rating: 4.9,
    isVerified: true,
    coordinates: { lat: 30.7046, lng: 76.7179 },
  },
  {
    id: "9",
    name: "Sunrise Pharmacy",
    ownerName: "Ravi Kumar",
    phoneNumber: "9876543218",
    address: "Rose Garden, Main Road",
    district: "Bathinda",
    mandal: "Bathinda Central",
    village: "Rose Garden",
    licenseNumber: "PB/BTI/2023/001",
    openingHours: "7:00 AM - 11:00 PM",
    services: ["Prescription Medicines", "OTC Drugs", "Health Checkup"],
    rating: 4.1,
    isVerified: false,
    coordinates: { lat: 30.2118, lng: 74.9455 },
  },
  {
    id: "10",
    name: "Apollo Pharmacy",
    ownerName: "Navdeep Singh",
    phoneNumber: "9876543219",
    address: "Sector 70, Phase 3",
    district: "Mohali",
    mandal: "Mohali West",
    village: "Sector 70",
    licenseNumber: "PB/MOH/2023/002",
    openingHours: "8:00 AM - 10:00 PM",
    services: ["Prescription Medicines", "Health Supplements", "Diagnostic Services"],
    rating: 4.5,
    isVerified: true,
    coordinates: { lat: 30.7, lng: 76.71 },
  },
]
